[build]
  publish = "rang-auto.ru"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/cars/*"
  to = "/.netlify/functions/cars"
  status = 200

[[redirects]]
  from = "/api/cars"
  to = "/.netlify/functions/cars"
  status = 200

[[redirects]]
  from = "/api/reviews/*"
  to = "/.netlify/functions/reviews"
  status = 200

[[redirects]]
  from = "/api/reviews"
  to = "/.netlify/functions/reviews"
  status = 200

[[redirects]]
  from = "/api/managers/*"
  to = "/.netlify/functions/managers"
  status = 200

[[redirects]]
  from = "/api/managers"
  to = "/.netlify/functions/managers"
  status = 200

[[redirects]]
  from = "/api/callback"
  to = "/.netlify/functions/callback"
  status = 200

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload"
  status = 200
